name: Automatic Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  prepare:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Release
        uses: codfish/semantic-release-action@6c65402abb31a48c3f7396d7d099da015be67c2b # v4.0.1
        with:
          branches: main
          additional-packages: |
           [
            '@semantic-release/changelog',
            '@semantic-release/git'
           ]
          plugins: |
           [
            '@semantic-release/commit-analyzer',
            '@semantic-release/release-notes-generator',
            '@semantic-release/changelog',
            '@semantic-release/github',
            '@semantic-release/git'
           ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          GIT_AUTHOR_NAME: 'zama-bot'
          GIT_COMMITTER_NAME: 'zama-bot'
          GIT_COMMITTER_EMAIL: 'zama-bot@zama.ai'
